# Generated by Django 3.2.16 on 2023-03-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_clients_client'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcription',
            new_name='Subscription',
        ),
    ]
